### ISSUE TITLE
UserIsNotServerUser

### ISSUE THREAD

**Issue by LarsBuur** [rmja/unicontarest#1]
Thank you very much for this code.

I got a lot of knowledge from reading it, but it is not clear how to properly authenticate. 

When I use my test account then I get a response from the auth action saying "UserIsNotServerUser".

Any tips?

best regards,
Lars Buur

**Comment by rmja** [comment]
Hi Lars,

You should authenticate using "Basic Auth" on each request. Could it be that the affiliate key/system id does not match the user being authenticated?

**Comment by LarsBuur** [comment]
Revisiting this I am not really sure how to obtain the "affiliate key/system id". I am able to compile and see the list of endpoints, but all calls to data endpoints fails

**Comment by rmja** [comment]
What error are you getting.

You get the affiliate key from uniconta by contacting their support.

man. 13. apr. 2020 18.54 skrev Lars Buur <notifications@github.com>:

**Comment by LarsBuur** [comment]
Thank you. I am able to connect and extract data from the API.
